# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(899, 461)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.GroupedDragging)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.frameGroup.setTitle("")
        self.frameGroup.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.frameGroup.setFlat(True)
        self.frameGroup.setCheckable(False)
        self.frameGroup.setObjectName("frameGroup")
        self._2 = QtWidgets.QVBoxLayout(self.frameGroup)
        self._2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self._2.setContentsMargins(0, 0, 0, 0)
        self._2.setSpacing(6)
        self._2.setObjectName("_2")
        self.frameList = FrameListView(self.frameGroup)
        self.frameList.setEnabled(True)
        self.frameList.setAcceptDrops(True)
        self.frameList.setDragEnabled(True)
        self.frameList.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.frameList.setAlternatingRowColors(False)
        self.frameList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.frameList.setFlow(QtWidgets.QListView.LeftToRight)
        self.frameList.setUniformItemSizes(True)
        self.frameList.setObjectName("frameList")
        self._2.addWidget(self.frameList)
        self.frameGroup2 = QtWidgets.QGroupBox(self.frameGroup)
        self.frameGroup2.setTitle("")
        self.frameGroup2.setFlat(True)
        self.frameGroup2.setObjectName("frameGroup2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameGroup2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.counter = QtWidgets.QLabel(self.frameGroup2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.counter.sizePolicy().hasHeightForWidth())
        self.counter.setSizePolicy(sizePolicy)
        self.counter.setObjectName("counter")
        self.horizontalLayout.addWidget(self.counter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.copy = QtWidgets.QToolButton(self.frameGroup2)
        icon = QtGui.QIcon.fromTheme("edit-copy")
        self.copy.setIcon(icon)
        self.copy.setObjectName("copy")
        self.horizontalLayout.addWidget(self.copy)
        self.moveLeft = QtWidgets.QToolButton(self.frameGroup2)
        icon = QtGui.QIcon.fromTheme("arrow-left")
        self.moveLeft.setIcon(icon)
        self.moveLeft.setArrowType(QtCore.Qt.NoArrow)
        self.moveLeft.setObjectName("moveLeft")
        self.horizontalLayout.addWidget(self.moveLeft)
        self.moveRight = QtWidgets.QToolButton(self.frameGroup2)
        icon = QtGui.QIcon.fromTheme("arrow-right")
        self.moveRight.setIcon(icon)
        self.moveRight.setArrowType(QtCore.Qt.NoArrow)
        self.moveRight.setObjectName("moveRight")
        self.horizontalLayout.addWidget(self.moveRight)
        self.splitBtn = QtWidgets.QToolButton(self.frameGroup2)
        self.splitBtn.setEnabled(True)
        icon = QtGui.QIcon.fromTheme("split")
        self.splitBtn.setIcon(icon)
        self.splitBtn.setObjectName("splitBtn")
        self.horizontalLayout.addWidget(self.splitBtn)
        self.importBtn = QtWidgets.QToolButton(self.frameGroup2)
        icon = QtGui.QIcon.fromTheme("document-import")
        self.importBtn.setIcon(icon)
        self.importBtn.setObjectName("importBtn")
        self.horizontalLayout.addWidget(self.importBtn)
        self.deleteBtn = QtWidgets.QToolButton(self.frameGroup2)
        icon = QtGui.QIcon.fromTheme("delete")
        self.deleteBtn.setIcon(icon)
        self.deleteBtn.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.deleteBtn.setAutoRaise(False)
        self.deleteBtn.setArrowType(QtCore.Qt.NoArrow)
        self.deleteBtn.setObjectName("deleteBtn")
        self.horizontalLayout.addWidget(self.deleteBtn)
        self._2.addWidget(self.frameGroup2)
        self.verticalLayout_2.addWidget(self.frameGroup)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 899, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_2.setFloating(False)
        self.dockWidget_2.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.preview = QtWidgets.QGraphicsView(self.dockWidgetContents_2)
        self.preview.setAutoFillBackground(False)
        self.preview.setInteractive(False)
        self.preview.setObjectName("preview")
        self.verticalLayout_3.addWidget(self.preview)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.duration = QtWidgets.QSpinBox(self.dockWidgetContents_2)
        self.duration.setWrapping(False)
        self.duration.setFrame(True)
        self.duration.setProperty("showGroupSeparator", False)
        self.duration.setMaximum(9999)
        self.duration.setProperty("value", 100)
        self.duration.setDisplayIntegerBase(10)
        self.duration.setObjectName("duration")
        self.horizontalLayout_5.addWidget(self.duration)
        self.reversible = QtWidgets.QCheckBox(self.dockWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reversible.sizePolicy().hasHeightForWidth())
        self.reversible.setSizePolicy(sizePolicy)
        self.reversible.setObjectName("reversible")
        self.horizontalLayout_5.addWidget(self.reversible)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.groupBox_3 = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.playPause = QtWidgets.QToolButton(self.groupBox_3)
        icon = QtGui.QIcon.fromTheme("media-playback-start")
        self.playPause.setIcon(icon)
        self.playPause.setObjectName("playPause")
        self.horizontalLayout_3.addWidget(self.playPause)
        self.goLeft = QtWidgets.QToolButton(self.groupBox_3)
        icon = QtGui.QIcon.fromTheme("media-skip-backward")
        self.goLeft.setIcon(icon)
        self.goLeft.setObjectName("goLeft")
        self.horizontalLayout_3.addWidget(self.goLeft)
        self.goRight = QtWidgets.QToolButton(self.groupBox_3)
        icon = QtGui.QIcon.fromTheme("media-skip-forward")
        self.goRight.setIcon(icon)
        self.goRight.setObjectName("goRight")
        self.horizontalLayout_3.addWidget(self.goRight)
        self.stop = QtWidgets.QToolButton(self.groupBox_3)
        icon = QtGui.QIcon.fromTheme("media-playback-stop")
        self.stop.setIcon(icon)
        self.stop.setObjectName("stop")
        self.horizontalLayout_3.addWidget(self.stop)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_2)
        self.sourcesGroup = QtWidgets.QDockWidget(MainWindow)
        self.sourcesGroup.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.sourcesGroup.setObjectName("sourcesGroup")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.subdirs = QtWidgets.QComboBox(self.dockWidgetContents_3)
        self.subdirs.setFrame(True)
        self.subdirs.setObjectName("subdirs")
        self.verticalLayout_5.addWidget(self.subdirs)
        self.sourcesList = FrameListView(self.dockWidgetContents_3)
        self.sourcesList.setProperty("showDropIndicator", False)
        self.sourcesList.setDragEnabled(True)
        self.sourcesList.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.sourcesList.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.sourcesList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.sourcesList.setObjectName("sourcesList")
        self.verticalLayout_5.addWidget(self.sourcesList)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.addFrame = QtWidgets.QPushButton(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addFrame.sizePolicy().hasHeightForWidth())
        self.addFrame.setSizePolicy(sizePolicy)
        self.addFrame.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon.fromTheme("node-add")
        self.addFrame.setIcon(icon)
        self.addFrame.setCheckable(False)
        self.addFrame.setDefault(True)
        self.addFrame.setFlat(False)
        self.addFrame.setObjectName("addFrame")
        self.horizontalLayout_4.addWidget(self.addFrame)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.addAll = QtWidgets.QToolButton(self.dockWidgetContents_3)
        icon = QtGui.QIcon.fromTheme("folder-add")
        self.addAll.setIcon(icon)
        self.addAll.setObjectName("addAll")
        self.horizontalLayout_4.addWidget(self.addAll)
        self.sort = QtWidgets.QToolButton(self.dockWidgetContents_3)
        icon = QtGui.QIcon.fromTheme("reverse")
        self.sort.setIcon(icon)
        self.sort.setObjectName("sort")
        self.horizontalLayout_4.addWidget(self.sort)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.sourcesGroup.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.sourcesGroup)
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-new")
        self.actionNew.setIcon(icon)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.actionSave.setIcon(icon)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-save-as")
        self.actionSave_as.setIcon(icon)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionClose = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("window-close")
        self.actionClose.setIcon(icon)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "libsuperderpy animation editor"))
        self.counter.setText(_translate("MainWindow", "-/-"))
        self.copy.setText(_translate("MainWindow", "Copy"))
        self.moveLeft.setText(_translate("MainWindow", "Left"))
        self.moveRight.setText(_translate("MainWindow", "Right"))
        self.splitBtn.setText(_translate("MainWindow", "Split"))
        self.importBtn.setText(_translate("MainWindow", "Import"))
        self.deleteBtn.setText(_translate("MainWindow", "Delete"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.dockWidget_2.setWindowTitle(_translate("MainWindow", "P&review"))
        self.duration.setSuffix(_translate("MainWindow", " ms"))
        self.duration.setPrefix(_translate("MainWindow", "Single frame duration: "))
        self.reversible.setText(_translate("MainWindow", "Reversible"))
        self.playPause.setText(_translate("MainWindow", "Play"))
        self.goLeft.setText(_translate("MainWindow", "-1"))
        self.goRight.setText(_translate("MainWindow", "+1"))
        self.stop.setText(_translate("MainWindow", "Stop"))
        self.sourcesGroup.setWindowTitle(_translate("MainWindow", "S&ources"))
        self.addFrame.setText(_translate("MainWindow", "Add frame"))
        self.addAll.setText(_translate("MainWindow", "Add all"))
        self.sort.setText(_translate("MainWindow", "Sort"))
        self.actionNew.setText(_translate("MainWindow", "&New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_as.setText(_translate("MainWindow", "Save &as..."))
        self.actionClose.setText(_translate("MainWindow", "&Close"))
from FrameListView import FrameListView
